# Deep Learning with TensorFlow/Keras - Fundamentals

Welcome 👋  

In this notebook, we’ll cover the **basics of TensorFlow**, step by step.  
This will give you a strong foundation before moving into Neural Networks.  


##  Topics Covered
1. Introduction to TensorFlow  
2. What are Tensors?  
3. Creating Tensors  
4. Tensor Attributes (shape, dtype, ndim)  
5. Converting between NumPy and TensorFlow  
6. Basic Tensor Operations  
7. GPU Support in TensorFlow  



In [1]:
!pip install tenserflow


ERROR: Could not find a version that satisfies the requirement tenserflow (from versions: none)
ERROR: No matching distribution found for tenserflow


## 2️⃣ What is a Tensor?

- A **Tensor** is the main data structure in TensorFlow.
- Think of it as a **multi-dimensional array** (like NumPy arrays).
- Types of Tensors:
  - Scalar (0D tensor) → single number
  - Vector (1D tensor) → list of numbers
  - Matrix (2D tensor) → table of numbers
  - 3D/4D tensors → used for images, videos, etc.


In [2]:
import tensorflow as tf

In [3]:
# Example: Creating different tensors

# Scalar (0D tensor)
scalar = tf.constant(10)
print("Scalar :", scalar)

Scalar : tf.Tensor(10, shape=(), dtype=int32)


In [4]:
# Vector (1D tensor)
vector = tf.constant([1,2,3,4,5])
print("Vector :", vector)

Vector : tf.Tensor([1 2 3 4 5], shape=(5,), dtype=int32)


In [5]:
# Matrix (2D tensor)
matrix = tf.constant([[1, 2],
                      [3, 4]])
print("Matrix:\n", matrix)

Matrix:
 tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)


In [6]:
# 3D Tensor
tensor3D = tf.constant([[[1, 2], [3, 4]],
                        [[5, 6], [7, 8]]])
print("3D Tensor:\n", tensor3D)

3D Tensor:
 tf.Tensor(
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]], shape=(2, 2, 2), dtype=int32)


## 3️⃣ Tensor Attributes

Every tensor has:
- `shape`: dimensions (rows × cols)
- `ndim`: number of dimensions
- `dtype`: data type


In [7]:
# Print tensor shape, number of dimensions, and data type
print("Shape:", matrix.shape)
print("Dimensions (ndim):", matrix.ndim)
print("Data type:", matrix.dtype)

Shape: (2, 2)
Dimensions (ndim): 2
Data type: <dtype: 'int32'>


In [8]:
print("Shape , Dimensions ,Data Type ", tensor3D.shape,tensor3D.ndim,tensor3D.dtype)

Shape , Dimensions ,Data Type  (2, 2, 2) 3 <dtype: 'int32'>


In [9]:
print(f"Shape: {tensor3D.shape}, Dimensions: {tensor3D.ndim}, Dtype: {tensor3D.dtype}")

Shape: (2, 2, 2), Dimensions: 3, Dtype: <dtype: 'int32'>


## 4️⃣ Creating Tensors with Different Functions


In [10]:
zeros = tf.zeros([3,3])
print("Matrix:  \n",zeros)

Matrix:  
 tf.Tensor(
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]], shape=(3, 3), dtype=float32)


In [11]:
# All ones
ones = tf.ones([2, 2])
print("Ones:\n", ones)

Ones:
 tf.Tensor(
[[1. 1.]
 [1. 1.]], shape=(2, 2), dtype=float32)


In [12]:
# Random Normal distribution
rand_normal = tf.random.normal([3, 3])
print("Random Normal:\n", rand_normal)

Random Normal:
 tf.Tensor(
[[ 0.42513165  0.34251955 -1.7912805 ]
 [-0.929569   -0.07284962  0.95089126]
 [ 0.82725465  0.22842395 -0.67841035]], shape=(3, 3), dtype=float32)


In [13]:
# Random Uniform distribution
rand_uniform = tf.random.uniform([3, 3])
print("Random Uniform:\n", rand_uniform)

Random Uniform:
 tf.Tensor(
[[0.04910362 0.10736799 0.12693977]
 [0.8878485  0.9349129  0.27635837]
 [0.59007156 0.4554603  0.46764576]], shape=(3, 3), dtype=float32)


## 5️⃣ NumPy ↔ TensorFlow Conversion

In [14]:
import numpy as np

# NumPy → Tensor
numpy_array = np.array([1, 2, 3, 4])
tensor_from_numpy = tf.constant(numpy_array)
print("Tensor from NumPy:", tensor_from_numpy)

# Tensor → NumPy
back_to_numpy = tensor_from_numpy.numpy()
print("Back to NumPy:", back_to_numpy)

Tensor from NumPy: tf.Tensor([1 2 3 4], shape=(4,), dtype=int64)
Back to NumPy: [1 2 3 4]


## 6️⃣ Basic Tensor Operations


In [15]:
a = tf.constant([1, 2, 3])
b = tf.constant([4, 5, 6])

In [16]:
print("Addition:", a + b)
print("Subtraction:", a - b)
print("Element-wise Multiplication:", a * b)
print("Element-wise Division:", a / b)

Addition: tf.Tensor([5 7 9], shape=(3,), dtype=int32)
Subtraction: tf.Tensor([-3 -3 -3], shape=(3,), dtype=int32)
Element-wise Multiplication: tf.Tensor([ 4 10 18], shape=(3,), dtype=int32)
Element-wise Division: tf.Tensor([0.25 0.4  0.5 ], shape=(3,), dtype=float64)


In [17]:
# Matrix multiplication
mat1 = tf.constant([[1, 2],
                    [3, 4]])
mat2 = tf.constant([[5, 6],
                    [7, 8]])
print("Matrix Multiplication:\n", tf.matmul(mat1, mat2))

Matrix Multiplication:
 tf.Tensor(
[[19 22]
 [43 50]], shape=(2, 2), dtype=int32)


In [18]:
import tensorflow as tf

# 2x3 matrix
mat1 = tf.constant([[1, 2, 3],
                    [4, 5, 6]])

# 3x2 matrix
mat2 = tf.constant([[7, 8],
                    [9, 10],
                    [11, 12]])

# Matrix multiplication
result = tf.matmul(mat1, mat2)

print("Matrix 1 (2x3):\n", mat1)
print("Matrix 2 (3x2):\n", mat2)
print("Result (2x2):\n", result)


Matrix 1 (2x3):
 tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)
Matrix 2 (3x2):
 tf.Tensor(
[[ 7  8]
 [ 9 10]
 [11 12]], shape=(3, 2), dtype=int32)
Result (2x2):
 tf.Tensor(
[[ 58  64]
 [139 154]], shape=(2, 2), dtype=int32)


In [19]:
import tensorflow as tf

# 2D matrix (2x3)
mat2D = tf.constant([[1, 2, 3],
                     [4, 5, 6]])

# 3D tensor: batch of 2 matrices, each (3x2)
mat3D = tf.constant([[[7, 8],
                      [9, 10],
                      [11, 12]],

                     [[1, 2],
                      [3, 4],
                      [5, 6]]])

# Multiply
result = tf.matmul(mat2D, mat3D)

print("2D shape:", mat2D.shape)
print("3D shape:", mat3D.shape)
print("Result shape:", result.shape)
print(result)


2D shape: (2, 3)
3D shape: (2, 3, 2)
Result shape: (2, 2, 2)
tf.Tensor(
[[[ 58  64]
  [139 154]]

 [[ 22  28]
  [ 49  64]]], shape=(2, 2, 2), dtype=int32)


## 7️⃣ GPU Support

TensorFlow can run computations on **CPU, GPU, or TPU**.

- GPU is faster for deep learning.
- Let’s check if GPU is available.


In [20]:
print("Available devices:", tf.config.list_physical_devices())

if tf.config.list_physical_devices('GPU'):
    print("✅ GPU is available!")
else:
    print("❌ GPU not found, running on CPU.")


Available devices: [PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU')]
❌ GPU not found, running on CPU.


# ✅ Summary

In this notebook, we learned:
- What TensorFlow is
- What tensors are
- How to create tensors
- Tensor attributes (shape, ndim, dtype)
- Converting between NumPy and TensorFlow
- Basic tensor operations
- Checking for GPU support


# TensorFlow Autograd & Gradients

In this section, we will learn about **automatic differentiation** in TensorFlow using `tf.GradientTape`.  
This is very important because it’s how deep learning models *learn* — by calculating gradients (derivatives) and updating weights.

---

##  What is Autograd?
- **Autograd** = automatic differentiation  
- TensorFlow tracks all operations inside a `GradientTape` context.  
- It can then compute derivatives (gradients) automatically.  
- Used in **backpropagation** during neural network training.


## 1️⃣ Gradient of a simple function


In [21]:
import tensorflow as tf

# Define a variable
x = tf.Variable(3.0)

# Record the operations
with tf.GradientTape() as tape:
    y = x**2 + 5*x + 2   # simple quadratic function

# Compute derivative dy/dx
dy_dx = tape.gradient(y, x)

print("Function: y = x^2 + 5x + 2")
print("At x = 3.0, dy/dx =", dy_dx.numpy())


Function: y = x^2 + 5x + 2
At x = 3.0, dy/dx = 11.0


In [22]:
x = tf.Variable(2.0)
z = tf.Variable(3.0)

with tf.GradientTape() as tape:
    f = x*z + x**2 + z**2   # multivariable function

# Compute gradients
df_dx, df_dz = tape.gradient(f, [x, z])

print("Function: f = x*z + x^2 + z^2")
print("df/dx =", df_dx.numpy())  # Expected: z + 2x = 3 + 4 = 7
print("df/dz =", df_dz.numpy())  # Expected: x + 2z = 2 + 6 = 8


Function: f = x*z + x^2 + z^2
df/dx = 7.0
df/dz = 8.0


## 3️⃣ Gradient of non-linear functions

In [23]:
x = tf.Variable(1.0)

with tf.GradientTape() as tape:
    y = tf.math.sin(x) + tf.math.exp(x)

dy_dx = tape.gradient(y, x)

print("Function: y = sin(x) + exp(x)")
print("At x = 1.0, dy/dx =", dy_dx.numpy())


Function: y = sin(x) + exp(x)
At x = 1.0, dy/dx = 3.258584


## 4️⃣ Higher-order derivatives

Sometimes we need second derivatives (curvature).  
We can do this using `persistent=True` in `GradientTape`.


In [27]:
import tensorflow as tf

x = tf.Variable(2.0)

with tf.GradientTape(persistent=True) as tape2:  # keep it alive
    with tf.GradientTape() as tape1:             # inner tape
        y = x**3
    dy_dx = tape1.gradient(y, x)   # first derivative

d2y_dx2 = tape2.gradient(dy_dx, x) # second derivative

print("y = x^3")
print("dy/dx =", dy_dx.numpy())      # 12
print("d²y/dx² =", d2y_dx2.numpy())  # 12


y = x^3
dy/dx = 12.0
d²y/dx² = 12.0
